# this config define the core elements of Dela to get a meaningful graph.
modname: go.dedis.ch/dela
includes:
    - go.dedis.ch/dela/*
excludes:
    - go.dedis.ch/dela/encoding*
    - go.dedis.ch/dela/crypto*
    - go.dedis.ch/dela/mino*
    - go.dedis.ch/dela$
    - go.dedis.ch/dela/dkg*
    - go.dedis.ch/dela/internal*
    - go.dedis.ch/dela/serde*
interfaces:
    - blockchain
    - consensus
    - cosi
    - dkg
    - ledger
    - ledger/arc
    - ledger/transactions
    - ledger/inventory
    - mino