name: Go test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    env:
      LLVL: trace
    steps:
    - name: Set up Go ^1.17
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Test with coverage
      if: matrix.platform == 'ubuntu-latest'
      run: go test -json -covermode=count -coverprofile=profile.cov ./... > report.json

    - name: Test without coverage
      if: matrix.platform == 'macos-latest' || matrix.platform == 'windows-latest'
      run: go test ./...
